---
- hosts: localhost
  tasks:
  - set_fact:
      vm_list:
        - name:  rancher1
        - name:  rancher2
        - name:  rancher3
      pool_dir: "/var/lib/libvirt/images"

  - name: destroy vm
    community.libvirt.virt:
      command: destroy
      name: "{{ item.name }}"
    loop: "{{ vm_list }}"

  - name: undefine vm
    community.libvirt.virt:
      command: undefine
      name: "{{ item.name }}"
    loop: "{{ vm_list }}"

  - name: 
    file:
      path: "{{ pool_dir }}/{{ item.name }}.qcow2"
      state: absent
    loop: "{{ vm_list }}"
